# Generated by Django 3.2.8 on 2021-10-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.freelancer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Job.joboffer'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.employer'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='needed_skills',
            field=models.ManyToManyField(blank=True, to='User.Skills'),
        ),
    ]
